### ISSUE TITLE
Bump to 4.0.7

### ISSUE THREAD

**Issue by LiterallyUniqueLogin** [conda-forge/bgen-reader-feedstock#44]
Hi there,

Can you bump this feedstock to v4.0.7? Alternatively, I'm happy to if you think all that's involved is changing the meta.yaml file. Or do you think there are changes needed to the build system?

@horta (not sure if you'd see this otherwise)

**Comment by horta** [comment]
Hi @LiterallyUniqueLogin , I'm happy to do but first I would need to submit [cbgen](https://github.com/limix/cbgen) to conda-forge first. I will see if I can submit it tomorrow.

**Comment by LiterallyUniqueLogin** [comment]
Awesome, thank you!

**Comment by LiterallyUniqueLogin** [comment]
Hey @horta,

Any updates?

**Comment by horta** [comment]
Yes, I bumped it to been 4.1.0. I've now pull requested cbgen: https://github.com/conda-forge/staged-recipes/pull/13214

Once that is done, I can upload the new bgen-reader.

**Comment by LiterallyUniqueLogin** [comment]
It looks like cbgen is now published on conda forge. Does that mean we can go ahead with bumping bgen-reader?

**Comment by horta** [comment]
Yes. It should be released in the next hours =)

**Comment by LiterallyUniqueLogin** [comment]
Thank you 😊
